# Generated by Django 2.0.6 on 2018-06-13 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_app', '0002_auto_20180613_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='tags',
            field=models.ManyToManyField(related_name='books', through='books_app.BooksTags', to='books_app.Tag'),
        ),
    ]
