# Generated by Django 2.0.6 on 2018-06-13 16:52

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('books_app', '0003_auto_20180613_1633'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='book',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
