# Generated by Django 2.0.6 on 2018-06-20 15:36

from django.db import migrations


# apps - все приложения из installed_apps
# schema_editor - для изменения бд
def migrate_tasks(apps, schema_editor):
    task = apps.get_model('myapp', 'Task')
    task.objects.create(text='Task 1', checked=False)
    task.objects.create(text='Task 2', checked=True)
    task.objects.create(text='Task 3', checked=False)
    task.objects.create(text='Task 4', checked=True)


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20180609_0825'),
    ]

    operations = [
        migrations.RunPython(migrate_tasks, migrations.RunPython.noop)
    ]
